name: Deploy Strapi

on:
  push:
    branches:
      - main
      - staging

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: ${{ github.ref_name == 'main' && 'main' || 'staging' }}

    steps:
      - uses: actions/checkout@v6
      - uses: webfactory/ssh-agent@v0.10.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
      - name: Deploy
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.VPS_USER }}@${{ secrets.VPS_IP }} << 'EOF'
            set -e

            export HISTFILE=/dev/null
            cd strapi
            git checkout ${{ github.ref_name }}
            echo "Pulling changes..."
            git pull
            echo "Building and starting..."

            # Secrets
            export ADMIN_JWT_SECRET=${{ secrets.ADMIN_JWT_SECRET }}
            export API_TOKEN_SALT=${{ secrets.API_TOKEN_SALT }}
            export APP_KEYS=${{ secrets.APP_KEYS }}
            export CLOUDFLARE_TUNNEL_TOKEN=${{ secrets.CLOUDFLARE_TUNNEL_TOKEN }}
            export DATABASE_PASSWORD=${{ secrets.DATABASE_PASSWORD }}
            export HETZNER_BUCKET_ACCESS_KEY_ID=${{ secrets.HETZNER_BUCKET_ACCESS_KEY_ID }}
            export HETZNER_BUCKET_ACCESS_SECRET=${{ secrets.HETZNER_BUCKET_ACCESS_SECRET }}
            export HETZNER_BUCKET_ENDPOINT=${{ secrets.HETZNER_BUCKET_ENDPOINT }}
            export HETZNER_BUCKET_HOST=${{ secrets.HETZNER_BUCKET_HOST }}
            export HETZNER_BUCKET_NAME=${{ secrets.HETZNER_BUCKET_NAME }}
            export HETZNER_BUCKET_REGION=${{ secrets.HETZNER_BUCKET_REGION }}
            export JWT_SECRET=${{ secrets.JWT_SECRET }}
            export TRANSFER_TOKEN_SALT=${{ secrets.TRANSFER_TOKEN_SALT }}

            # Vars
            export DOCKER_NETWORK_NAME=${{ vars.DOCKER_NETWORK_NAME }}
            export NGINX_SERVER_NAME=${{ vars.NGINX_SERVER_NAME }}

            docker compose -f docker-compose.prod.yml up -d --build
          EOF
