name: Deploy app to donate.magicgrants.org

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: main

    steps:
      - uses: actions/checkout@v4
      - uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
      - name: Deploy
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.VPS_USER }}@${{ secrets.VPS_IP }} << 'EOF'
            export HISTFILE=/dev/null
            cd strapi
            echo "Pulling changes..."
            git pull
            echo "Building and starting..."

            APP_KEYS=${{ secrets.APP_KEYS }} \
            API_TOKEN_SALT=${{ secrets.API_TOKEN_SALT }} \
            JWT_SECRET=${{ secrets.JWT_SECRET }} \
            ADMIN_JWT_SECRET=${{ secrets.ADMIN_JWT_SECRET }} \
            TRANSFER_TOKEN_SALT=${{ secrets.TRANSFER_TOKEN_SALT }} \
            DATABASE_PASSWORD=${{ secrets.DATABASE_PASSWORD }} \
            AWS_ACCESS_KEY_ID: ${ secrets.AWS_ACCESS_KEY_ID } \
            AWS_ACCESS_SECRET: ${ secrets.AWS_ACCESS_SECRET } \
            AWS_REGION: ${{ secrets.AWS_REGION }} \
            AWS_BUCKET: ${{ secrets.AWS_BUCKET }} \
            CDN_URL: ${{ secrets.CDN_URL }} \
            CDN_ROOT_PATH: ${{ secrets.CDN_ROOT_PATH }} \
            CLOUDFLARE_TUNNEL_TOKEN=${{ secrets.CLOUDFLARE_TUNNEL_TOKEN }} \
            docker compose -f docker-compose.prod.yml up -d --build
          EOF
